version: "3.8"
services:
  backend:
    build:
      context: ./School
    ports:
      - "8000:8000"

  front-end:
    build:
      context: ./student-system
    ports:
      - "4200:4200"
    depends_on:
      - backend